import { useRouter } from "next/router";
import Head from "next/head";
import Sidebar from "../components/Sidebar";
import TransactionsTable from "../components/TransactionsTable";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/Navbar";

import { useState } from "react";


export default function Dashboard() {

  const router = useRouter();
  const { name } = router.query;

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/logo.png" /> */}
      </Head>

      <main className="flex bg-transparent text-black w-[100%]" data-theme="emerald">
        <div className="flex flex-col items-cente justify-cente py-8 w-[0%] lg:w-[40%]">
            <div className="text-red">
                <Sidebar/>
            </div>
          </div>
          <div className="lg:ml-5 w-[100%] lg:w-[60%] py-10 px-10 flex flex-col bg-[#f6f9ff]">
                <div className="flex flex-row justify-between">
                  <div className="flex flex-row gap-5">
                    <h6 className="text-3xl font-bold mb-5">Welcome {name}! </h6>
                   </div>
                  <div className="flex flex-row gap-5">
                    <button><Image /></button>
                    {/* <ConnectButton showBalance={false} /> */}
                  </div>
                </div>

                
            <div className="flex flex-wrap">
                
            </div>
            </div>
      </main>
    </div>
  );
}

