// import { useRouter } from "next/router";
// import Head from "next/head";
// import Sidebar from "../components/Sidebar";
// import TransactionsTable from "../components/TransactionsTable";
// import Image from "next/image";
// import Link from "next/link";
// import Navbar from "../components/Navbar";

// import { useState } from "react";


// export default function Dashboard() {

//   const router = useRouter();
//   const { name } = router.query;

//   return (
//     <div>
//       <Head>
//         <title>Dashboard</title>
//         <meta name="description" content="Generated by create next app" />
//         {/* <link rel="icon" href="/logo.png" /> */}
//       </Head>

//       <main className="flex bg-transparent text-black w-[100%]" data-theme="emerald">
//         <div className="flex flex-col items-cente justify-cente py-8 w-[0%] lg:w-[40%]">
//             <div className="text-red">
//                 <Sidebar/>
//             </div>
//           </div>
//           <div className="lg:ml-5 w-[100%] lg:w-[60%] py-10 px-10 flex flex-col bg-[#f6f9ff]">
//                 <div className="flex flex-row justify-between">
//                   <div className="flex flex-row gap-5">
//                     <h6 className="text-3xl font-bold mb-5">Welcome {name}! </h6>
//                    </div>
//                   <div className="flex flex-row gap-5">
//                     <button><Image /></button>
//                     {/* <ConnectButton showBalance={false} /> */}
//                   </div>
//                 </div>

                
//             <div className="flex flex-wrap">
                
//             </div>
//             </div>
//       </main>
//     </div>
//   );
// }



import React from 'react';

const Dashboard = () => {
  return (
    <div className="flex">
      {/* Sidebar */}
      <div className="w-1/4 p-4 bg-gray-200">
        <div className="mb-4">
          {/* Campaign Metrics */}
          <h2 className="text-lg font-bold mb-2">Campaign Metrics</h2>
          <table className="w-full mb-4">
            <tbody>
              <tr>
                <td className="py-2">Aggregate CPM:</td>
                <td className="py-2">[CPM value]</td>
              </tr>
              <tr>
                <td className="py-2">Total Impressions:</td>
                <td className="py-2">[Impressions value]</td>
              </tr>
              <tr>
                <td className="py-2">Rate per Mile:</td>
                <td className="py-2">[Rate per Mile value]</td>
              </tr>
              <tr>
                <td className="py-2">Miles Driven:</td>
                <td className="py-2">[Miles Driven value]</td>
              </tr>
              <tr>
                <td className="py-2">Cost of the Campaign:</td>
                <td className="py-2">[Campaign cost value]</td>
              </tr>
            </tbody>
          </table>
          {/* Horizontal line */}
          <hr className="my-4" />
        </div>
        {/* Units */}
        <div>
          <h2 className="text-lg font-bold mb-2">Units</h2>
          <table className="w-full">
            <thead>
              <tr>
                <th className="py-2">Unit</th>
                <th className="py-2">Miles Driven</th>
                <th className="py-2">Cost</th>
                <th className="py-2">Impression</th>
                <th className="py-2">CPM</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="py-2">[Unit value]</td>
                <td className="py-2">[Miles Driven value]</td>
                <td className="py-2">[Cost value]</td>
                <td className="py-2">[Impression value]</td>
                <td className="py-2">[CPM value]</td>
              </tr>
              {/* More rows */}
            </tbody>
          </table>
        </div>
      </div>
      {/* Map area */}
      <div className="w-3/4 bg-gray-500">
        {/* Map component */}
      </div>
    </div>
  );
};

export default Dashboard;
