import Head from "next/head";
import Login from "./login"
import { League_Spartan } from 'next/font/google'

const league = League_Spartan({ subsets: ['latin'] })


export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Truckable</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      
      <main
        className="overflow-x-hidden bg-[#F6F6F6] text-black"
        data-theme="emerald"
      >
          <Login/>
      </main>
    </div>
       
  );
}
